interface StoryBrief {
  yourStory: string;
  storyArc: string;
  theHook: string;
  theStakes: string;
  theTension: string;
  thePayoff: string;
  theReframe: string;
  beatSuggestions: string[];
  titleIdeas: string[];
  warning: string;
}

export function briefToText(
  brief: StoryBrief,
  projectDescription: string
): string {
  return `YOUR STORY BRIEF
${"=".repeat(60)}

PROJECT
${projectDescription}

YOUR STORY
${brief.yourStory}

STORY ARC
${brief.storyArc}

THE HOOK
${brief.theHook}

THE STAKES
${brief.theStakes}

THE TENSION
${brief.theTension}

THE PAYOFF
${brief.thePayoff}

THE REFRAME
${brief.theReframe}

SUGGESTED BEATS
${brief.beatSuggestions.map((b, i) => `${String(i + 1).padStart(2, "0")}. ${b}`).join("\n")}

TITLE IDEAS
${brief.titleIdeas.map((t) => `- ${t}`).join("\n")}

WATCH OUT
${brief.warning}

${"=".repeat(60)}
Generated by The Storyteller Engine — jespermakes.com/storyteller
`;
}

export function briefToMarkdown(
  brief: StoryBrief,
  projectDescription: string
): string {
  return `# Your Story Brief

> **Project:** ${projectDescription}

## Your Story

${brief.yourStory}

**Story arc:** ${brief.storyArc}

---

## The Hook
${brief.theHook}

## The Stakes
${brief.theStakes}

## The Tension
${brief.theTension}

## The Payoff
${brief.thePayoff}

---

## The Reframe

> *${brief.theReframe}*

---

## Suggested Beats

${brief.beatSuggestions.map((b, i) => `${i + 1}. ${b}`).join("\n")}

## Title Ideas

${brief.titleIdeas.map((t) => `- ${t}`).join("\n")}

---

## Watch Out

${brief.warning}

---

*Generated by [The Storyteller Engine](https://jespermakes.com/storyteller)*
`;
}

export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
