export interface PrintSettingsInput {
  designName: string;
  heightMm?: number;
  topDiameterMm?: number;
  bottomDiameterMm?: number;
  wallThicknessMm?: number;
}

/**
 * Generate a plain-text print settings card for a lamp design.
 */
export function generatePrintSettingsText(input: PrintSettingsInput): string {
  const name = input.designName || "Lamp";
  const divider = "─".repeat(44);

  const lines: string[] = [
    divider,
    `  PRINT SETTINGS — ${name}`,
    divider,
    "",
    "  SLICER",
    "  • Mode:      Vase mode (spiralize outer contour)",
    "  • Nozzle:    0.6 mm recommended",
    "  • Layer:     0.3 mm (or 50% of nozzle diameter)",
    "  • Speed:     30–40 mm/s for clean walls",
    "",
    "  MATERIAL",
    "  • Filament:  Translucent PETG",
    "  • Bed temp:  75–80 °C",
    "  • Nozzle:    230–245 °C",
    "  • Note:      Translucent material gives best",
    "                light diffusion through the walls",
    "",
    "  HARDWARE",
    "  • Bulb:      Standard E27 LED bulb",
    "  • Wattage:   Max 12 W LED (low heat output)",
  ];

  if (
    input.heightMm !== undefined ||
    input.topDiameterMm !== undefined ||
    input.bottomDiameterMm !== undefined ||
    input.wallThicknessMm !== undefined
  ) {
    lines.push("", "  DIMENSIONS");
    if (input.heightMm !== undefined)
      lines.push(`  • Height:         ${input.heightMm.toFixed(1)} mm`);
    if (input.topDiameterMm !== undefined)
      lines.push(`  • Top diameter:   ${input.topDiameterMm.toFixed(1)} mm`);
    if (input.bottomDiameterMm !== undefined)
      lines.push(`  • Bottom diameter:${input.bottomDiameterMm.toFixed(1)} mm`);
    if (input.wallThicknessMm !== undefined)
      lines.push(`  • Wall thickness: ${input.wallThicknessMm.toFixed(1)} mm`);
  }

  lines.push(
    "",
    divider,
    "  Generated by jespermakes.com/lamp-designer",
    divider,
    "",
  );

  return lines.join("\n");
}

/**
 * Trigger a browser download of the print settings as a .txt file.
 */
export function downloadPrintSettings(
  input: PrintSettingsInput,
  filename: string = "print-settings.txt",
): void {
  const text = generatePrintSettingsText(input);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
