import { readdirSync, statSync, readFileSync } from "fs";
import { join, relative, extname } from "path";
import imageSize from "image-size";
import { db } from "../lib/db";
import { images } from "../lib/db/schema";
import { eq } from "drizzle-orm";
import { autoTagImage } from "../lib/image-ai";

const PUBLIC_IMAGES_DIR = join(process.cwd(), "public", "images");
const SUPPORTED_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);
const BASE_URL = "https://jespermakes.com";

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const s = statSync(p);
    if (s.isDirectory()) walk(p, acc);
    else if (SUPPORTED_EXT.has(extname(p).toLowerCase())) acc.push(p);
  }
  return acc;
}

async function run() {
  const files = walk(PUBLIC_IMAGES_DIR);
  console.log(`Found ${files.length} images under public/images/`);

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const absPath of files) {
    const relPath = relative(join(process.cwd(), "public"), absPath).replace(/\\/g, "/");
    const urlPath = `/${relPath}`;
    const fullUrl = `${BASE_URL}${urlPath}`;

    const existing = await db.select().from(images).where(eq(images.url, urlPath)).limit(1);
    if (existing.length) {
      skipped++;
      continue;
    }

    let width: number | null = null;
    let height: number | null = null;
    let sizeBytes = 0;
    try {
      const buf = readFileSync(absPath);
      const size = imageSize(buf);
      width = size.width ?? null;
      height = size.height ?? null;
      sizeBytes = buf.byteLength;
    } catch (e) {
      console.warn(`probe failed for ${urlPath}`, e);
    }

    let ai = null;
    try {
      ai = await autoTagImage(fullUrl);
      console.log(`✓ tagged ${urlPath}`);
    } catch (e) {
      console.warn(`AI tag failed for ${urlPath}:`, e);
      failed++;
    }

    const filename = urlPath.split("/").pop() || urlPath;

    await db.insert(images).values({
      source: "public",
      url: urlPath,
      pathname: relPath,
      filename,
      width,
      height,
      sizeBytes,
      mimeType: mimeFromExt(extname(absPath)),
      description: ai?.description ?? null,
      material: ai?.material ?? null,
      sponsors: ai?.sponsors ?? [],
      toolCategories: ai?.toolCategories ?? [],
      shotType: ai?.shotType ?? null,
      who: ai?.who ?? [],
      setting: ai?.setting ?? null,
      descriptionAutoGenerated: !!ai?.description,
      tagsAutoGenerated: !!ai,
      reviewed: false,
    });

    created++;
    await sleep(400);
  }

  console.log(`\nDone. Created: ${created}, skipped: ${skipped}, AI-failed: ${failed}`);
  process.exit(0);
}

function mimeFromExt(ext: string) {
  const m: Record<string, string> = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
    ".avif": "image/avif",
  };
  return m[ext.toLowerCase()] ?? "application/octet-stream";
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
