import { db } from "../lib/db";
import { images } from "../lib/db/schema";
import { eq, and } from "drizzle-orm";
import { autoTagImage } from "../lib/image-ai";

async function run() {
  const rows = await db
    .select()
    .from(images)
    .where(and(eq(images.reviewed, false), eq(images.hidden, false)));

  console.log(`Found ${rows.length} unreviewed images to retag`);

  let success = 0;
  let failed = 0;

  for (const image of rows) {
    const fullUrl = image.source === "public"
      ? `https://jespermakes.com${image.url}`
      : image.url;

    try {
      const ai = await autoTagImage(fullUrl);
      await db
        .update(images)
        .set({
          description: ai.description || image.description,
          material: ai.material,
          sponsors: ai.sponsors,
          toolCategories: ai.toolCategories,
          shotType: ai.shotType,
          who: ai.who,
          setting: ai.setting,
          descriptionAutoGenerated: true,
          tagsAutoGenerated: true,
          updatedAt: new Date(),
        })
        .where(eq(images.id, image.id));
      console.log(`✓ ${image.filename}`);
      success++;
    } catch (e) {
      console.warn(`✗ ${image.filename}:`, e);
      failed++;
    }
    await sleep(400);
  }

  console.log(`\nDone. Success: ${success}, failed: ${failed}`);
  process.exit(0);
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
