import { exportSVG, downloadSVG } from "./export-svg";
import type { Shape } from "./types";

export type ExportProfile =
  | "generic"
  | "shaper-origin"
  | "laser"
  | "cnc-router";

export const PROFILE_LABELS: Record<ExportProfile, string> = {
  generic: "Generic SVG",
  "shaper-origin": "Shaper Origin SVG",
  laser: "Laser Cutter SVG",
  "cnc-router": "CNC Router SVG",
};

export const PROFILE_DESCRIPTIONS: Record<ExportProfile, string> = {
  generic: "Works with any SVG-aware tool (Inkscape, Illustrator…).",
  "shaper-origin":
    "Color-encoded for Shaper Origin: black=interior, blue=exterior, red=on-line, gray=guide.",
  laser:
    "Hairline strokes for laser software (LightBurn, LaserGRBL, Glowforge): red=cut, blue=score, black=raster.",
  "cnc-router":
    "Closed paths only, plus a .json job sheet sidecar with material + bit notes.",
};

const PROFILE_STORAGE_KEY = "studio_export_profile";

/** Read the most-recently-used profile (from localStorage). */
export function readLastProfile(): ExportProfile {
  if (typeof window === "undefined") return "generic";
  try {
    const v = localStorage.getItem(PROFILE_STORAGE_KEY);
    if (
      v === "generic" ||
      v === "shaper-origin" ||
      v === "laser" ||
      v === "cnc-router"
    ) {
      return v;
    }
  } catch {
    /* noop */
  }
  return "generic";
}

export function rememberProfile(profile: ExportProfile): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(PROFILE_STORAGE_KEY, profile);
  } catch {
    /* noop */
  }
}

/* ----------------------------- Profile maps ---------------------------- */

function shaperColorize(s: Shape): Shape {
  // Without cut-type metadata, default everything to "interior cut" (black).
  // Filled shapes lose the fill so cuts read as outlines.
  return {
    ...s,
    stroke: "#000000",
    fill: "none",
  };
}

function laserize(s: Shape): Shape {
  // Default everything to "cut" (red) with hairline stroke. Filled shapes
  // become unfilled cut outlines for v1; raster pockets are a Phase 5 thing.
  return {
    ...s,
    stroke: "#FF0000",
    strokeWidth: 0.001,
    fill: "none",
  };
}

function isClosed(s: Shape): boolean {
  if (s.type === "rectangle" || s.type === "circle") return true;
  if (s.type === "line") return false;
  if (s.type === "text") return false;
  if (s.type === "path") return s.closed === true;
  return false;
}

interface ProfileResult {
  svg: string;
  sidecar?: { filename: string; content: string };
}

function exportGeneric(shapes: Shape[]): ProfileResult {
  return { svg: exportSVG(shapes) };
}

function exportShaperOrigin(shapes: Shape[]): ProfileResult {
  return { svg: exportSVG(shapes.map(shaperColorize)) };
}

function exportLaser(shapes: Shape[]): ProfileResult {
  return { svg: exportSVG(shapes.map(laserize)) };
}

function exportCncRouter(
  shapes: Shape[],
  designName: string,
): ProfileResult {
  const closed = shapes.filter(isClosed);
  const skipped = shapes.length - closed.length;
  const svg = exportSVG(closed);
  const minX = -1;
  void minX; // bbox is computed inside exportSVG; sidecar uses our own.
  const bounds = computeBounds(closed);
  const sidecar = {
    generator: "Jesper Makes Studio",
    version: 1,
    designName,
    exportDate: new Date().toISOString(),
    units: "mm",
    boundingBox: bounds
      ? {
          width: Math.round((bounds.maxX - bounds.minX) * 1000) / 1000,
          height: Math.round((bounds.maxY - bounds.minY) * 1000) / 1000,
        }
      : { width: 0, height: 0 },
    shapesSkipped: skipped,
    shapes: closed.map((s) => ({
      id: s.id,
      type: s.type,
      suggestedCutType: "profile",
      dimensions: { width: s.width, height: s.height },
    })),
    notes:
      "Generated by Jesper Makes Studio. Open the SVG in your CAM software and assign toolpaths. Open paths, lines, and text were skipped.",
  };
  return {
    svg,
    sidecar: {
      filename: filenameForJobSheet(designName),
      content: JSON.stringify(sidecar, null, 2),
    },
  };
}

function computeBounds(
  shapes: Shape[],
): { minX: number; minY: number; maxX: number; maxY: number } | null {
  if (shapes.length === 0) return null;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const s of shapes) {
    minX = Math.min(minX, s.x - s.width / 2);
    minY = Math.min(minY, s.y - s.height / 2);
    maxX = Math.max(maxX, s.x + s.width / 2);
    maxY = Math.max(maxY, s.y + s.height / 2);
  }
  return { minX, minY, maxX, maxY };
}

function safeSlug(name: string): string {
  return (
    name
      .replace(/[^a-z0-9-_ ]/gi, "")
      .replace(/\s+/g, "-")
      .toLowerCase() || "design"
  );
}

function filenameForExport(name: string, profile: ExportProfile): string {
  const slug = safeSlug(name);
  switch (profile) {
    case "generic":
      return `${slug}.svg`;
    case "shaper-origin":
      return `${slug}-shaper.svg`;
    case "laser":
      return `${slug}-laser.svg`;
    case "cnc-router":
      return `${slug}-cnc.svg`;
  }
}

function filenameForJobSheet(name: string): string {
  return `${safeSlug(name)}-cnc.job.json`;
}

export function exportWithProfile(
  shapes: Shape[],
  profile: ExportProfile,
  designName: string,
): ProfileResult {
  switch (profile) {
    case "generic":
      return exportGeneric(shapes);
    case "shaper-origin":
      return exportShaperOrigin(shapes);
    case "laser":
      return exportLaser(shapes);
    case "cnc-router":
      return exportCncRouter(shapes, designName);
  }
}

export function downloadProfileExport(
  shapes: Shape[],
  profile: ExportProfile,
  designName: string,
): void {
  const result = exportWithProfile(shapes, profile, designName);
  downloadSVG(result.svg, filenameForExport(designName, profile));
  if (result.sidecar) {
    if (typeof window === "undefined") return;
    const blob = new Blob([result.sidecar.content], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement("a");
    a.href = url;
    a.download = result.sidecar.filename;
    window.document.body.appendChild(a);
    a.click();
    window.document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
