import type { Shape } from "./types";
import { shapesBounds } from "./geometry";
import { pointsToSVGPath } from "./path-ops";

const PADDING_MM = 10;

function escapeXmlAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function formatNumber(n: number): string {
  if (!Number.isFinite(n)) return "0";
  // Trim to 4 decimals, drop trailing zeros.
  const fixed = n.toFixed(4);
  return fixed.replace(/\.?0+$/, "");
}

function shapeAttrs(shape: Shape): string {
  const stroke = `stroke="${escapeXmlAttr(shape.stroke)}"`;
  const strokeWidth = `stroke-width="${formatNumber(shape.strokeWidth)}"`;
  const fill = `fill="${escapeXmlAttr(shape.fill)}"`;
  const transform = shape.rotation
    ? ` transform="rotate(${formatNumber(shape.rotation)}, ${formatNumber(shape.x)}, ${formatNumber(shape.y)})"`
    : "";
  return `${stroke} ${strokeWidth} ${fill}${transform}`;
}

function shapeToSvg(shape: Shape): string | null {
  const attrs = shapeAttrs(shape);
  if (shape.type === "rectangle") {
    const x = shape.x - shape.width / 2;
    const y = shape.y - shape.height / 2;
    const maxR = Math.min(shape.width, shape.height) / 2;
    const r = shape.cornerRadius
      ? Math.max(0, Math.min(maxR, shape.cornerRadius))
      : 0;
    const radii = r > 0 ? ` rx="${formatNumber(r)}" ry="${formatNumber(r)}"` : "";
    return `<rect x="${formatNumber(x)}" y="${formatNumber(y)}" width="${formatNumber(shape.width)}" height="${formatNumber(shape.height)}"${radii} ${attrs} />`;
  }
  if (shape.type === "circle") {
    const rx = shape.width / 2;
    const ry = shape.height / 2;
    if (Math.abs(rx - ry) < 1e-6) {
      return `<circle cx="${formatNumber(shape.x)}" cy="${formatNumber(shape.y)}" r="${formatNumber(rx)}" ${attrs} />`;
    }
    return `<ellipse cx="${formatNumber(shape.x)}" cy="${formatNumber(shape.y)}" rx="${formatNumber(rx)}" ry="${formatNumber(ry)}" ${attrs} />`;
  }
  if (shape.type === "text") {
    const text = shape.text ?? "";
    const fontSize = shape.fontSize ?? 10;
    const fontFamily = shape.fontFamily ?? "Inter, sans-serif";
    const anchor = shape.textAnchor ?? "middle";
    const lineHeight = fontSize * 1.2;
    const lines = text.split("\n");
    const startDy = -((lines.length - 1) * lineHeight) / 2;
    const fill = `fill="${escapeXmlAttr(shape.stroke)}"`;
    const transform = shape.rotation
      ? ` transform="rotate(${formatNumber(shape.rotation)}, ${formatNumber(shape.x)}, ${formatNumber(shape.y)})"`
      : "";
    const tspans = lines
      .map(
        (line, i) =>
          `<tspan x="${formatNumber(shape.x)}" dy="${formatNumber(i === 0 ? startDy : lineHeight)}">${escapeXml(line)}</tspan>`,
      )
      .join("");
    return `<text x="${formatNumber(shape.x)}" y="${formatNumber(shape.y)}" font-size="${formatNumber(fontSize)}" font-family="${escapeXmlAttr(fontFamily)}" text-anchor="${anchor}" dominant-baseline="middle" ${fill}${transform}>${tspans}</text>`;
  }
  if (shape.type === "path") {
    const d =
      shape.pathData ??
      pointsToSVGPath(shape.points ?? [], shape.closed ?? false);
    if (!d) return null;
    return `<path d="${escapeXmlAttr(d)}" ${attrs} />`;
  }
  if (shape.type === "line") {
    const x1 = shape.x + (shape.x1 ?? 0);
    const y1 = shape.y + (shape.y1 ?? 0);
    const x2 = shape.x + (shape.x2 ?? 0);
    const y2 = shape.y + (shape.y2 ?? 0);
    const stroke = `stroke="${escapeXmlAttr(shape.stroke)}"`;
    const strokeWidth = `stroke-width="${formatNumber(shape.strokeWidth)}"`;
    const transform = shape.rotation
      ? ` transform="rotate(${formatNumber(shape.rotation)}, ${formatNumber(shape.x)}, ${formatNumber(shape.y)})"`
      : "";
    return `<line x1="${formatNumber(x1)}" y1="${formatNumber(y1)}" x2="${formatNumber(x2)}" y2="${formatNumber(y2)}" ${stroke} ${strokeWidth} stroke-linecap="round"${transform} />`;
  }
  return null;
}

export function exportSVG(shapes: Shape[]): string {
  const bounds = shapesBounds(shapes) ?? {
    minX: 0,
    minY: 0,
    maxX: 100,
    maxY: 100,
  };
  const minX = bounds.minX - PADDING_MM;
  const minY = bounds.minY - PADDING_MM;
  const width = bounds.maxX - bounds.minX + PADDING_MM * 2;
  const height = bounds.maxY - bounds.minY + PADDING_MM * 2;

  const body = shapes
    .map(shapeToSvg)
    .filter((s): s is string => s !== null)
    .join("\n  ");

  return [
    `<?xml version="1.0" encoding="UTF-8" standalone="no"?>`,
    `<!-- Generated by Jesper Makes Studio - jespermakes.com -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="${formatNumber(width)}mm" height="${formatNumber(height)}mm" viewBox="${formatNumber(minX)} ${formatNumber(minY)} ${formatNumber(width)} ${formatNumber(height)}">`,
    `  ${body}`,
    `</svg>`,
    "",
  ].join("\n");
}

export function downloadSVG(svgString: string, filename: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([svgString], { type: "image/svg+xml" });
  const url = URL.createObjectURL(blob);
  const a = window.document.createElement("a");
  a.href = url;
  a.download = filename;
  window.document.body.appendChild(a);
  a.click();
  window.document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
