import { NextRequest, NextResponse } from "next/server";
import { put } from "@vercel/blob";
import imageSize from "image-size";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { images } from "@/lib/db/schema";
import { eq, desc, sql, and, ilike, or } from "drizzle-orm";
import { autoTagImage } from "@/lib/image-ai";

export const runtime = "nodejs";
export const maxDuration = 60;

async function requireAdmin() {
  const session = await auth();
  if (!session?.user?.email || session.user.email !== process.env.ADMIN_EMAIL) {
    return null;
  }
  return session;
}

export async function GET(request: NextRequest) {
  const session = await requireAdmin();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(request.url);
  const query = searchParams.get("q")?.trim() || "";
  const untaggedOnly = searchParams.get("untagged") === "true";
  const material = searchParams.get("material") || "";
  const shotType = searchParams.get("shotType") || "";
  const tag = searchParams.get("tag") || "";

  const conditions = [eq(images.hidden, false)];

  if (untaggedOnly) {
    conditions.push(eq(images.reviewed, false));
  }
  if (material) conditions.push(eq(images.material, material));
  if (shotType) conditions.push(eq(images.shotType, shotType));
  if (tag) {
    conditions.push(
      sql`(
        ${tag} = ANY(${images.customTags})
        OR ${tag} = ANY(${images.toolCategories})
        OR ${tag} = ANY(${images.sponsors})
        OR ${tag} = ANY(${images.who})
      )`
    );
  }
  if (query) {
    const q = `%${query}%`;
    conditions.push(
      or(
        ilike(images.description, q),
        ilike(images.filename, q),
        sql`EXISTS (SELECT 1 FROM unnest(${images.customTags}) AS t WHERE t ILIKE ${q})`,
      )!
    );
  }

  const rows = await db
    .select()
    .from(images)
    .where(and(...conditions))
    .orderBy(desc(images.reviewed), desc(images.updatedAt))
    .limit(500);

  const stats = await db
    .select({
      total: sql<number>`count(*)::int`,
      untagged: sql<number>`count(*) filter (where not ${images.reviewed})::int`,
    })
    .from(images)
    .where(eq(images.hidden, false));

  return NextResponse.json({
    images: rows,
    stats: stats[0] ?? { total: 0, untagged: 0 },
  });
}

export async function POST(request: NextRequest) {
  const session = await requireAdmin();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const formData = await request.formData();
  const file = formData.get("file");

  if (!(file instanceof File)) {
    return NextResponse.json({ error: "No file provided" }, { status: 400 });
  }

  const maxBytes = 20 * 1024 * 1024;
  if (file.size > maxBytes) {
    return NextResponse.json({ error: "File too large (max 20MB)" }, { status: 413 });
  }

  const allowedTypes = ["image/jpeg", "image/png", "image/webp", "image/avif"];
  if (!allowedTypes.includes(file.type)) {
    return NextResponse.json({ error: "Unsupported file type" }, { status: 415 });
  }

  const arrayBuffer = await file.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);

  let width: number | null = null;
  let height: number | null = null;
  try {
    const size = imageSize(buffer);
    width = size.width ?? null;
    height = size.height ?? null;
  } catch {
  }

  const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "-").toLowerCase();
  const blob = await put(`uploads/${safeName}`, buffer, {
    access: "public",
    addRandomSuffix: true,
    contentType: file.type,
  });

  let aiResult = null;
  try {
    aiResult = await autoTagImage(blob.url);
  } catch (err) {
    console.error("autoTagImage failed", err);
  }

  const [inserted] = await db
    .insert(images)
    .values({
      source: "blob",
      url: blob.url,
      pathname: blob.pathname,
      filename: file.name,
      width,
      height,
      sizeBytes: file.size,
      mimeType: file.type,
      description: aiResult?.description ?? null,
      material: aiResult?.material ?? null,
      sponsors: aiResult?.sponsors ?? [],
      toolCategories: aiResult?.toolCategories ?? [],
      shotType: aiResult?.shotType ?? null,
      who: aiResult?.who ?? [],
      setting: aiResult?.setting ?? null,
      descriptionAutoGenerated: !!aiResult?.description,
      tagsAutoGenerated: !!aiResult,
      reviewed: false,
      uploadedByUserId: session.user?.id,
    })
    .returning();

  return NextResponse.json({ image: inserted });
}
