import { z } from "zod";
import { eq, or } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { db } from "@/lib/db";
import { images } from "@/lib/db/schema";
import type { ToolContext } from "./index";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function registerUpdateImageMetadata(server: McpServer, _ctx: ToolContext) {
  server.registerTool(
    "update_image_metadata",
    {
      title: "Update image metadata",
      description:
        "Update an image's description and/or tags. Identify the image by UUID, filename, or pathname. Pass only the fields you want to change. Use this after looking at an image (via its public URL) to write back the description and tags.",
      inputSchema: {
        imageIdOrPath: z
          .string()
          .min(1)
          .describe("The image's UUID, filename, or pathname."),
        description: z
          .string()
          .max(2000)
          .optional()
          .describe(
            "Description of the image, 1-2 sentences. Also used as alt text.",
          ),
        tags: z
          .array(z.string())
          .optional()
          .describe(
            "Array of lowercase, hyphen-separated custom tags. Use existing library taxonomy when applicable.",
          ),
      },
    },
    async ({ imageIdOrPath, description, tags }) => {
      const looksLikeUuid =
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
          imageIdOrPath,
        );

      const condition = looksLikeUuid
        ? or(
            eq(images.id, imageIdOrPath),
            eq(images.filename, imageIdOrPath),
            eq(images.pathname, imageIdOrPath),
          )
        : or(
            eq(images.filename, imageIdOrPath),
            eq(images.pathname, imageIdOrPath),
          );

      const existing = await db
        .select()
        .from(images)
        .where(condition!)
        .limit(1);

      if (existing.length === 0) {
        return {
          isError: true,
          content: [
            {
              type: "text" as const,
              text: `No image found matching "${imageIdOrPath}".`,
            },
          ],
        };
      }

      const image = existing[0];

      const patch: Partial<typeof images.$inferInsert> = {
        updatedAt: new Date(),
        reviewed: true,
        tagsAutoGenerated: false,
      };

      if (description !== undefined) patch.description = description;
      if (tags !== undefined) patch.customTags = tags;

      if (description === undefined && tags === undefined) {
        return {
          content: [
            {
              type: "text" as const,
              text: "No changes provided. Pass at least one of: description, tags.",
            },
          ],
        };
      }

      await db
        .update(images)
        .set(patch)
        .where(eq(images.id, image.id));

      revalidatePath("/admin/images");

      const changed = [];
      if (description !== undefined) changed.push("description");
      if (tags !== undefined) changed.push("customTags");

      return {
        content: [
          {
            type: "text" as const,
            text: `Updated metadata for "${image.filename}". Changed: ${changed.join(", ")}. Marked as reviewed.`,
          },
        ],
      };
    },
  );
}
