import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { images } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { isValidTagValue } from "@/data/image-tag-vocabulary";

export const runtime = "nodejs";

async function requireAdmin() {
  const session = await auth();
  if (!session?.user?.email || session.user.email !== process.env.ADMIN_EMAIL) return null;
  return session;
}

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  const session = await requireAdmin();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const rows = await db.select().from(images).where(eq(images.id, params.id)).limit(1);
  if (!rows.length) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json({ image: rows[0] });
}

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  const session = await requireAdmin();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await request.json();

  const updates: Record<string, unknown> = { updatedAt: new Date(), reviewed: true };

  if (typeof body.description === "string") {
    updates.description = body.description.slice(0, 500);
    updates.descriptionAutoGenerated = false;
  }
  if ("material" in body) {
    updates.material =
      body.material === null || body.material === ""
        ? null
        : isValidTagValue("material", body.material)
        ? body.material
        : null;
  }
  if ("shotType" in body) {
    updates.shotType =
      body.shotType === null || body.shotType === ""
        ? null
        : isValidTagValue("shotType", body.shotType)
        ? body.shotType
        : null;
  }
  if ("setting" in body) {
    updates.setting =
      body.setting === null || body.setting === ""
        ? null
        : isValidTagValue("setting", body.setting)
        ? body.setting
        : null;
  }
  if (Array.isArray(body.subjects)) {
    updates.subjects = body.subjects.filter((s: unknown): s is string =>
      typeof s === "string" && isValidTagValue("subjects", s)
    );
  }
  if (Array.isArray(body.who)) {
    updates.who = body.who.filter((s: unknown): s is string =>
      typeof s === "string" && isValidTagValue("who", s)
    );
  }
  if (Array.isArray(body.customTags)) {
    updates.customTags = body.customTags
      .filter((s: unknown): s is string => typeof s === "string")
      .map((s: string) => s.trim().toLowerCase().slice(0, 40))
      .filter((s: string) => s.length > 0 && s.length < 40)
      .slice(0, 20);
  }
  if (typeof body.tagsAutoGenerated === "boolean") {
    updates.tagsAutoGenerated = body.tagsAutoGenerated;
  }

  const [updated] = await db
    .update(images)
    .set(updates)
    .where(eq(images.id, params.id))
    .returning();

  if (!updated) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json({ image: updated });
}

export async function DELETE(_req: NextRequest, { params }: { params: { id: string } }) {
  const session = await requireAdmin();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const [updated] = await db
    .update(images)
    .set({ hidden: true, updatedAt: new Date() })
    .where(eq(images.id, params.id))
    .returning();

  if (!updated) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json({ ok: true });
}
