import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { images } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { autoTagImage } from "@/lib/image-ai";

export const runtime = "nodejs";
export const maxDuration = 60;

export async function POST(_req: NextRequest, { params }: { params: { id: string } }) {
  const session = await auth();
  if (!session?.user?.email || session.user.email !== process.env.ADMIN_EMAIL) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const rows = await db.select().from(images).where(eq(images.id, params.id)).limit(1);
  const image = rows[0];
  if (!image) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const fullUrl = image.source === "public"
    ? `https://jespermakes.com${image.url}`
    : image.url;

  const result = await autoTagImage(fullUrl);

  const [updated] = await db
    .update(images)
    .set({
      description: result.description || image.description,
      material: result.material,
      sponsors: result.sponsors,
      toolCategories: result.toolCategories,
      shotType: result.shotType,
      who: result.who,
      setting: result.setting,
      descriptionAutoGenerated: true,
      tagsAutoGenerated: true,
      updatedAt: new Date(),
    })
    .where(eq(images.id, params.id))
    .returning();

  return NextResponse.json({ image: updated, suggested: result });
}
